---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
<<<<<<< HEAD
        image: docker.io/kostiscodefresh/simple-env-app:2.0
=======
        image: docker.io/kostiscodefresh/simple-env-app:3.0
>>>>>>> bd4c79d3345cba5961c6278bb44e5ecfa655996e
